### ISSUE TITLE
`Lein run` does not start a webserver

### ISSUE THREAD

**Issue by crantok** [marick/enlive-tutorial#1]
I see the output below. Do I need to do something other than `lein run`?

```
$ lein run
Retrieving org/clojure/clojure-contrib/1.2.0/clojure-contrib-1.2.0.pom from central
Retrieving postgresql/postgresql/8.4-702.jdbc4/postgresql-8.4-702.jdbc4.pom from central
Retrieving org/clojure/java.jdbc/0.0.3/java.jdbc-0.0.3.pom from central
Retrieving enlive/enlive/1.0.0/enlive-1.0.0.pom from clojars
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.
```

**Comment by marick** [comment]
Thanks, and sorry for the delay. (I've been in Europe, on mixed business and pleasure.) 

I'm no longer a Clojure user, but it looks as if `lein run` has tightened up security. Notice how out-of-date the tutorial is: it's still loading the (long abandoned) user-contributed library from Clojure 1.2. It may help to use the most current version of `enlive`.

As mentioned in another issue, I'll give you access if you want to fix it.
