### ISSUE TITLE
Link to jcrit is broken

### ISSUE THREAD

**Issue by crantok** [marick/enlive-tutorial#2]
The in README.md to jcrit is 404

**Comment by marick** [comment]
Thanks, and sorry for the delay. (I've been in Europe, on mixed business and pleasure.) 

I'm no longer a Clojure user, so I won't be fixing this. If you (or anyone else) would like to fix it, I'll give you contributor access.

**Comment by crantok** [comment]
Thanks for the offer but I've never used Clojure. I had read about Enlive and was interested in trying it out. I've since found out that it's pretty similar to Ruby's Nokogiri so I'm using that instead.
